name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup build
        uses: ./.github/npm
      - name: Run go build
        run: make build

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup golang
        uses: ./.github/golang
      - name: go test
        run: make unit
